### ISSUE TITLE
Showing a blank screen on logging in

### ISSUE THREAD

**Issue by vaibhav541** [Aga-Ma/e-learning-portal#9]
After i logged in , its showing just a blank screen with a logout option and a heading course list

**Comment by Aga-Ma** [comment]
Hi, sorry that I didn't respond to your query. I never thought that I'll back to this project as it was created for self-learning purpose.
It was an expected behavior to see empty courses list as there were no courses data in DB.
I've created a simple script that fills some data in DB in courses/management. Now to have some example courses you need to run `python manage.py filldb`.
